#!/bin/bash
#
# This file is part of Liri.
#
# Copyright (C) 2016 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# $BEGIN_LICENSE:GPL3+$
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# $END_LICENSE$
#

set -e

machine=all
init=0

while test -n "$1"; do
  case "$1" in
    "--help" | "-h")
      echo "Usage: $0 [--init] [machine name]"
      return 0
      ;;
    "--init")
      init=1
      ;;
    *)
      machine=$1
    ;;
  esac
  shift
done

if [ "$machine" = "all" ]; then
    cmd="./scripts/build-all.sh"
else
    cmd="./scripts/build-machine.sh $machine"
fi

if [ $init -eq 1 ]; then
    ./lirios-init-build-env init --device $machine
fi
exec sudo docker run -it --rm -v $(pwd):$(pwd) --workdir $(pwd) ubuntubuild $cmd
