#
# This file is part of Liri.
#
# Copyright (C) 2017 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# $BEGIN_LICENSE:GPL3+$
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# $END_LICENSE$
#

FLUID_GIT_BRANCH = "develop"
QTACCOUNTSSERVICE_GIT_BRANCH = "develop"
QTGSETTINGS_GIT_BRANCH = "develop"
VIBE_GIT_BRANCH = "develop"
LIRI_GIT_BRANCH = "develop"
LIRI_BROWSER_GIT_BRANCH = "develop"
LIRI_CALCULATOR_GIT_BRANCH = "develop"
LIRI_TEXT_GIT_BRANCH = "develop"
LIRI_APPCENTER_GIT_BRANCH = "develop"
LIRI_FILES_GIT_BRANCH = "develop"
LIRI_TERMINAL_GIT_BRANCH = "develop"

FLUID_VERSION = "0.11.0"
QTACCOUNTSSERVICE_VERSION = "1.1.0"
QTGSETTINGS_VERSION = "1.1.0"
VIBE_VERSION = "0.9.0"
BROWSER_VERSION = "0.0.0"
CALCULATOR_VERSION = "1.0.0"
TEXT_VERSION = "0.2.0"
APPCENTER_VERSION = "0.1.0"
FILES_VERSION = "0.1.0"
TERMINAL_VERSION = "0.1.0"
LIRI_VERSION = "0.9.0"

SRCREV = "${AUTOREV}"
